### ISSUE TITLE
Problem s pull request

### ISSUE THREAD

**Issue by HanzlovaPavlina** [naucse/prezencka#105]
Ahoj,
učím se pracovat Githubem podle návodu na http://pyladies.cz/ostrava/
Ale zasekla jsem se. Nikde nemohu najít tlačítko Compare and pull request, o němž se na stránkách v části Spolupráce a Open Source píše. Už jsem svůj textový soubor nasdílela do mého naklonovaného repozitáře... 
(https://github.com/HanzlovaPavlina/prezencka - soubor pavlina.txt)

Můžu poprosit o radu? Díky moc

**Comment by encukou** [comment]
Ahoj,
Jestli tam není "Compare and pull request", běž na https://github.com/HanzlovaPavlina/prezencka a mělo by tam být šedé tlačítko "New pull request".

**Comment by encukou** [comment]
Povedlo se?

**Comment by HanzlovaPavlina** [comment]
Ted se mi povedlo odeslat žádost... tedy doufám :)
Díky za radu.

2017-02-13 15:05 GMT+01:00 Petr Viktorin <notifications@github.com>:
